server:
  port: 8885

target-host: localhost

spring:
  redis:
    host: ${target-host}
    redisson:
      file: classpath:redisson.yml

  rabbitmq:
    apiUrl: http://${target-host}:15672/api/
    host: ${target-host}
    port: 5672
    username: user
    password: bitnami

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      type: batch
      ack-mode: manual
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: false
      # 默认500ms
      fetch-max-wait: 1000
      # 默认500
      max-poll-records: 100

track:
  etcd:
    url: http://${target-host}:2379
  zookeeper:
    url: ${target-host}:2181

  #服务端的地址
  serverUrl: http://localhost:8885


appName: etcd-rabbit-example

#debug: true
